= Application Overview
include::_attributes.adoc[]

== Architecture

Here is a simplified architecture diagram of the application:

[.bordershadow]
image::05/application-architecture.drawio.svg[]


The different components are:

- The **frontend**: the application itself, developed using the Patternfly framework (React, Typescript), running in the browser of the user.
- The **backend**: a Python FastAPI application, running in a container on {ocp}. It handles the communication with the database, the LLM, and the Object storage. It handles the communication with the frontend by exposing a REST API.
- The **database**: a PostgreSQL database, running in a container on {ocp}. It stores the claims.
- The **LLM**: the language model used to summarize and extract information from the claims. It is consumed by the backend through its API.
- The **VectorDB**: the vector database used to store documents for retrieval in the RAG part. It's based on Milvus.
- The **Object storage**: an S3-compatible object storage. It stores the claim images.

The application has already been built as a container image that we are now ready to deploy using GitOps. You can head to the next section.